services:
  app:    
    container_name: api-gateway-service
    build: .
    working_dir: /app
    volumes: 
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://localhost:3002
      - USER_SERVICE_URL=http://localhost:3001
      - RESTAURANT_SERVICE_URL=http://localhost:3003
      